BEGIN;

DROP TABLE IF EXISTS USERS, POSTS, COMMENTS, VOTES CASCADE;

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD TEXT NOT NULL,
    AVATAR TEXT NOT NULL DEFAULT 'https://www.seekpng.com/png/detail/110-1100707_person-avatar-placeholder.png'
);

CREATE TABLE POSTS(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    USER_ID INT NOT NULL,
    CONSTRAINT USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMMENTS(
    ID SERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    USER_ID INT NOT NULL,
    POST_ID INT NOT NULL,
    CONSTRAINT USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT POST_ID FOREIGN KEY(POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE VOTES(
    ID SERIAL PRIMARY KEY,
    VOTES_UP INT,
    VOTES_DOWN INT,
    USER_ID INT NOT NULL,
    POST_ID INT,
    COMMENT_ID INT,
    CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_POST_ID FOREIGN KEY(POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_COMMENT_ID FOREIGN KEY(COMMENT_ID) REFERENCES COMMENTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);


COMMIT;